# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  db:
    # We use the predefined Postgres image
    image: postgres:11.4
    ports: 
      - "5432:5432"
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petfinder_dev
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data
    restart: always
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata: